apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober-oncall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prober-oncall
  template:
    metadata:
      labels:
        app: prober-oncall
    spec:
      containers:
        - name: prober-oncall
          image: prober_oncall:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: prober-oncall-service
spec:
  selector:
    app: prober-oncall
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP